services:
  app:
    container_name: test_spendbase
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - PROTOCOL=${PROTOCOL}
      - HOST=${HOST}
      - DATABASE_HOST=db
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - OPENWEATHERMAP_API_KEY=${OPENWEATHERMAP_API_KEY}
      - OPENWEATHERMAP_URL=${OPENWEATHERMAP_URL}
    depends_on:
      - db
    command: ["sh", "-c", "until pg_isready -h db -p 5432; do sleep 1; done; npm run start"]
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
volumes:
  postgres_data:
    driver: local      
