services:
  app:
    build: .
    ports:
      - "3333:3333"
    environment:
      - PORT=3333
      - PROTOCOL=http
      - HOST=localhost
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=admin
      - DATABASE_NAME=spendbase
      - OPENWEATHERMAP_API_KEY=c6eb53f350a02b020b20686c3678143f
      - OPENWEATHERMAP_URL=https://api.openweathermap.org/data/2.5/weather
    depends_on:
      - db
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spendbase
    ports:
      - "5432:5432"
